services:
  augur:
    image: ghcr.io/mayvqt/augur:latest
    build: .
    container_name: augur
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/data
